use_frameworks!

platform :ios, '10.0'

target 'GrubPaySDK_Example' do
  pod 'GrubPaySDK', :path => '../'

  target 'GrubPaySDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
